# Generated by Django 5.0.1 on 2024-01-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='valor',
            new_name='value',
        ),
    ]
