# Generated by Django 5.0.1 on 2024-01-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_rename_fecha_data_date_rename_valor_data_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
