# Generated by Django 5.0.1 on 2024-01-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
