# Generated by Django 5.0.1 on 2024-01-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0011_alter_data_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
