# Generated by Django 5.0.1 on 2024-01-19 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0012_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(24.0), django.core.validators.MaxValueValidator(29.9)])),
            ],
        ),
    ]
