# Generated by Django 5.0.1 on 2024-01-19 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0013_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(24.0), django.core.validators.MaxValueValidator(29.91)]),
        ),
    ]
